---
- hosts: WP-DOCKER
  remote_user: bdwapp 
  become: yes
  tasks:
    - name: "Executa o container MySQL"
      docker_container:
        name: bdwordpress
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Password123
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: Password123

    - name: "Executa o container WordPress"
      docker_container:
        name: wordpress
        image: wordpress
        env:
          WORDPRESS_DB_HOST: bdwordpress:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: Password123
        links:
          - "bdwordpress:mysql"
        ports:
          - "80:80"
